mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
  type-aliases-package: com.prj.web.*.*.mapper
spring:
  datasource:
    username: jsz0426
    url: jdbc:mysql://1.234.53.49:3306/project
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '@Jsz0426'
  thymeleaf:
    suffix: .html
server:
  port: '8090'

springdoc:
  # 기본값: application/json
  # request media type 의 기본 값
  default-consumes-media-type: application/json

  # 기본값: */*
  # response media type 의 기본 값
  default-produces-media-type: application/json

  # 스웨거에서 제공하는 ui 라이브러리 설정
  swagger-ui:

    #   기본 값 : /swagger-ui.html
    #   Swagger HTML 문서 경로
    path: /swagger-ui.html

    #   swagger-ui를 사용할 것인지 여부
    enabled: true

  # 스웨거 api문서 설정
  api-docs:

    #   기본값 : /v3/api-docs
    #   spring boot 웹 애플리케이션의 api를 OpenAPI 3을 이용하여 json 형식화 한것의 경로
    path: /swagger/api-docs

    #   스웨거 api문서를 사용할지 여부
    enabled: true